apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-app
  name: spring-service
  namespace: kafka
spec:
  selector:
    app: spring-boot-app
  type: LoadBalancer
  ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot-app
  name: spring-boot-app
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: springio/gs-spring-boot-docker
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-broker:9092

